# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7dd43bc2979856d8b9dccbc379410c4490b684da5532a290cd1616aad6c10252a98f3c9043d840ee5a76609dbc0c6c20eb1bda24e89f1caef247ba9fb90b578

test:
  secret_key_base: d373cf85ed63fa1077d56d827382212f20350b361457d5f41949f62bcb896209f8b4c1e1277e1b96766038730e4f5814e59b427a6a461e867d5c6af873904e2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
